# Generated by Django 4.1.6 on 2023-02-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontent',
            name='sub_content',
            field=models.TextField(default=-0.1),
            preserve_default=False,
        ),
    ]
