# Generated by Django 4.1.6 on 2023-02-04 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_subcontent_sub_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcontentimage',
            old_name='image',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='subcontent',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subcontent', to='blog.article'),
        ),
        migrations.AlterField(
            model_name='subcontentimage',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontentimage', to='blog.subcontent'),
        ),
        migrations.AlterField(
            model_name='subcontentimage',
            name='is_wide',
            field=models.BooleanField(),
        ),
    ]
